BRICK = {
    "brick_num": 27,
    "brick_title": "Mechanisms of Acid-Base Transport",
    "games": [
        {
            "slug": "nephron_segments_bicarb_reabsorption",
            "title": "Nephron Segments and Acid-Base Transport",
            "subtitle": "Match nephron segments to their bicarbonate handling roles",
            "categories": ["Bicarbonate Handling", "Key Transporter or Cell", "Notable Feature"],
            "data": {
                "Proximal Tubule": {
                    "Bicarbonate Handling": "Reabsorbs 70-80% of filtered bicarbonate via CO2 shuttle",
                    "Key Transporter or Cell": "NHE3 antiporter and NBCe1 sodium-bicarbonate cotransporter",
                    "Notable Feature": "Site of ammoniagenesis from glutamine metabolism"
                },
                "Thick Ascending Limb": {
                    "Bicarbonate Handling": "Reabsorbs about 15% of filtered bicarbonate",
                    "Key Transporter or Cell": "Reabsorbs NH4+ which dissociates to NH3 in medulla",
                    "Notable Feature": "Supplies medullary NH3 for collecting duct trapping"
                },
                "Collecting Duct (alpha cells)": {
                    "Bicarbonate Handling": "Generates new bicarbonate while secreting H+",
                    "Key Transporter or Cell": "H+-ATPase and H+/K+-ATPase pumps",
                    "Notable Feature": "Determines final urine pH down to 4.6"
                },
                "Collecting Duct (beta cells)": {
                    "Bicarbonate Handling": "Actively secretes bicarbonate during alkalosis",
                    "Key Transporter or Cell": "Pendrin Cl-/HCO3- exchanger on apical side",
                    "Notable Feature": "Alkalinizes urine up to pH 8.0"
                }
            }
        },
        {
            "slug": "buffers_and_acid_excretion",
            "title": "Urinary Buffers and Net Acid Excretion",
            "subtitle": "Match each buffer or molecule to its role in acid excretion",
            "categories": ["Where It Comes From", "Role in Acid Handling", "Clinical Note"],
            "data": {
                "Bicarbonate (HCO3-)": {
                    "Where It Comes From": "Filtered at glomerulus, over 4000 mmol per day",
                    "Role in Acid Handling": "Primary blood buffer reclaimed in proximal tubule",
                    "Clinical Note": "Acetazolamide blocks reclamation causing metabolic acidosis"
                },
                "Phosphate (Titratable Acid)": {
                    "Where It Comes From": "Passively filtered weak acid from blood",
                    "Role in Acid Handling": "Binds H+ in tubule to form H2PO4 buffer",
                    "Clinical Note": "Reduced filtration in CKD limits acid excretion"
                },
                "Ammonium (NH4+)": {
                    "Where It Comes From": "Made in proximal tubule from glutamine metabolism",
                    "Role in Acid Handling": "Traps secreted H+ distally and exits in urine",
                    "Clinical Note": "Hyperkalemia inhibits ammoniagenesis causing type 4 RTA"
                },
                "Carbonic Anhydrase": {
                    "Where It Comes From": "Enzyme in tubular lumen and proximal tubule cells",
                    "Role in Acid Handling": "Catalyzes HCO3- to CO2 plus water conversion",
                    "Clinical Note": "Inhibited by acetazolamide used for altitude sickness"
                },
                "New Bicarbonate": {
                    "Where It Comes From": "Generated by alpha-intercalated cells and ammoniagenesis",
                    "Role in Acid Handling": "Replaces bicarbonate consumed buffering fixed acids",
                    "Clinical Note": "Stimulated by systemic acidosis and aldosterone"
                }
            }
        },
        {
            "slug": "acid_base_disturbances_renal_response",
            "title": "Disturbances and Renal Response",
            "subtitle": "Match each acid-base condition to the kidney's response",
            "categories": ["Effect on Bicarbonate Reabsorption", "Effect on H+ or NH4+ Secretion", "Typical Clinical Result"],
            "data": {
                "Systemic Acidosis": {
                    "Effect on Bicarbonate Reabsorption": "Increases proximal tubule bicarbonate reabsorption",
                    "Effect on H+ or NH4+ Secretion": "Stimulates H+ secretion and ammoniagenesis",
                    "Typical Clinical Result": "Lowers urine pH toward minimum value 4.6"
                },
                "Systemic Alkalosis": {
                    "Effect on Bicarbonate Reabsorption": "Reduces proximal tubule bicarbonate reabsorption",
                    "Effect on H+ or NH4+ Secretion": "Beta cells secrete bicarbonate via pendrin exchanger",
                    "Typical Clinical Result": "Alkalinizes urine toward pH 8.0"
                },
                "Volume Depletion": {
                    "Effect on Bicarbonate Reabsorption": "Increases bicarbonate reabsorption with sodium retention",
                    "Effect on H+ or NH4+ Secretion": "Aldosterone stimulates H+ secretion in collecting duct",
                    "Typical Clinical Result": "Maintains metabolic alkalosis until volume restored"
                },
                "Hypokalemia": {
                    "Effect on Bicarbonate Reabsorption": "Increases proximal tubule HCO3- reabsorption",
                    "Effect on H+ or NH4+ Secretion": "Raises H+ secretion via intracellular acidosis",
                    "Typical Clinical Result": "Causes or maintains metabolic alkalosis"
                },
                "Hyperkalemia": {
                    "Effect on Bicarbonate Reabsorption": "Limits new bicarbonate generation in proximal tubule",
                    "Effect on H+ or NH4+ Secretion": "Inhibits ammoniagenesis and ammonium secretion",
                    "Typical Clinical Result": "Causes type 4 hyperkalemic renal tubular acidosis"
                },
                "Chronic Kidney Disease": {
                    "Effect on Bicarbonate Reabsorption": "Reduced filtered load limits handling of bicarbonate",
                    "Effect on H+ or NH4+ Secretion": "Impaired ammoniagenesis lowers acid excretion",
                    "Typical Clinical Result": "Non-anion gap metabolic acidosis (NAGMA)"
                }
            }
        }
    ]
}
