BRICK = {
    "brick_num": 46,
    "brick_title": "Postinfectious Glomerulonephritis",
    "games": [
        {
            "slug": "pign_clinical_presentation",
            "title": "PIGN Clinical Presentation",
            "subtitle": "Match each clinical feature to its description in postinfectious glomerulonephritis.",
            "categories": ["Description", "Timing or Cause", "Significance"],
            "data": {
                "Hematuria": {
                    "Description": "Asymptomatic microscopic hematuria or gross hematuria with dysmorphic RBCs and RBC casts",
                    "Timing or Cause": "Caused by inflammation allowing red blood cells to leak through the GBM",
                    "Significance": "Often extreme enough to make urine appear tea colored or cola colored"
                },
                "Edema": {
                    "Description": "Periorbital and peripheral swelling, often dramatic with children swollen up overnight",
                    "Timing or Cause": "Results from sodium and fluid retention due to acute glomerular injury",
                    "Significance": "Classic component of the nephritic syndrome presentation in PIGN"
                },
                "Hypertension": {
                    "Description": "Elevated blood pressure on examination as part of nephritic syndrome",
                    "Timing or Cause": "Caused by volume overload from impaired glomerular filtration of sodium",
                    "Significance": "One of three classic nephritic findings alongside hematuria and edema"
                },
                "Post-pharyngitis onset": {
                    "Description": "Renal symptoms appear after a recent sore throat infection in the patient",
                    "Timing or Cause": "Develops 1 to 3 weeks after Streptococcus pyogenes pharyngitis exposure",
                    "Significance": "Classic timing pattern of poststreptococcal glomerulonephritis in children worldwide"
                },
                "Post-skin infection onset": {
                    "Description": "Renal symptoms follow a strep skin infection like impetigo or cellulitis",
                    "Timing or Cause": "Develops 3 to 6 weeks after a Streptococcus skin infection exposure",
                    "Significance": "Longer delay than pharyngitis-associated PSGN due to slower immune response onset"
                },
                "Staph-associated onset": {
                    "Description": "Glomerular disease appears within first few days after infection appearance",
                    "Timing or Cause": "Caused by Staphylococcus in hospitalized adults with endocarditis or pneumonia",
                    "Significance": "Lacks the several-week delay seen in PSGN and needs prompt antibiotics"
                }
            }
        },
        {
            "slug": "pign_pathophysiology_immunology",
            "title": "PIGN Pathophysiology and Immunology",
            "subtitle": "Match each pathophysiology component to its role in PIGN glomerular injury.",
            "categories": ["What It Is", "Role in PIGN", "Clinical Result"],
            "data": {
                "Type III hypersensitivity": {
                    "What It Is": "Immune reaction mediated by circulating antigen-antibody immune complex deposition in tissues",
                    "Role in PIGN": "Shared mechanism by which different infectious agents trigger glomerular damage in kidney",
                    "Clinical Result": "Produces the acute nephritic syndrome typical of postinfectious glomerulonephritis presentation"
                },
                "IgG immune complexes": {
                    "What It Is": "Circulating antibodies generated by infections that bind microbial or self antigens",
                    "Role in PIGN": "Deposit in glomerulus at subepithelial and mesangial locations along the GBM",
                    "Clinical Result": "Seen on electron microscopy as dome-shaped humps along subepithelial GBM"
                },
                "Complement activation": {
                    "What It Is": "Cascade of serum proteins triggered by trapped immune complexes in the glomerulus",
                    "Role in PIGN": "Alternative pathway is activated, bypassing classical pathway components C2 and C4",
                    "Clinical Result": "Causes phagocyte recruitment, inflammation, tissue damage, and low serum C3 levels"
                },
                "Molecular mimicry": {
                    "What It Is": "Bacterial antigens have configurations similar to human proteins triggering cross-reactivity",
                    "Role in PIGN": "One proposed theory for why some infections cause PIGN and others do not",
                    "Clinical Result": "Specific strep strains commonly cause strep pharyngitis and trigger nephritogenic response"
                },
                "Streptococcus pyogenes": {
                    "What It Is": "Group A beta-hemolytic Streptococcus bacterium and most common cause of PIGN",
                    "Role in PIGN": "Causes PSGN; specific strains contain antigens that set off systemic immune response",
                    "Clinical Result": "Renal disease starts weeks after pharyngitis or after a strep skin infection"
                },
                "Staphylococcus": {
                    "What It Is": "Bacterium increasingly causing PIGN in hospitalized adults in the United States",
                    "Role in PIGN": "Stimulates complement-mediated immune attack on the glomerulus through immune complexes",
                    "Clinical Result": "Develops within days of severe infection like endocarditis, cellulitis, osteomyelitis, or pneumonia"
                }
            }
        },
        {
            "slug": "pign_diagnosis_management",
            "title": "PIGN Diagnosis and Management",
            "subtitle": "Match each workup or treatment item to its purpose and findings in PIGN.",
            "categories": ["What It Shows or Does", "When Used", "Key Detail"],
            "data": {
                "Urinalysis": {
                    "What It Shows or Does": "Shows RBCs, dysmorphic RBCs, and RBC casts, all signs of glomerular disease",
                    "When Used": "First-line test when nephritic syndrome is suspected after a recent infection",
                    "Key Detail": "Variable protein may appear, but it seldom reaches the nephrotic range"
                },
                "Serum C3 level": {
                    "What It Shows or Does": "Detects low serum concentration of C3 complement from uncontrolled alternative pathway activation",
                    "When Used": "Routinely checked during workup to support a clinical diagnosis of PIGN",
                    "Key Detail": "Decreased in 90 percent of cases, while C4 typically remains normal"
                },
                "Antistreptolysin O titer": {
                    "What It Shows or Does": "Serologic test detecting antibodies against streptococcal antigens after recent strep infection",
                    "When Used": "Useful when no documentation of past streptococcal illness like a throat culture",
                    "Key Detail": "Elevated titer or Streptozyme test confirms preceding streptococcal infection in PSGN"
                },
                "Renal biopsy": {
                    "What It Shows or Does": "Shows enlarged hypercellular glomeruli with neutrophils and dome-shaped subepithelial humps",
                    "When Used": "Rarely needed; performed if disease does not reverse or GFR is declining",
                    "Key Detail": "Helps rule out another glomerular disease if presentation is severe or atypical"
                },
                "Supportive therapy": {
                    "What It Shows or Does": "Manages symptoms with loop diuretics like furosemide for fluid removal in patients",
                    "When Used": "Primary treatment for children because natural course of the disease is short",
                    "Key Detail": "Condition resolves in 1 to 2 weeks on its own in most pediatric cases"
                },
                "Penicillin V antibiotic": {
                    "What It Shows or Does": "Provides Gram-positive coverage against the most common bacterial organisms causing PIGN",
                    "When Used": "Adults with staphylococcal infections needing prompt antibiotic treatment to prevent complications",
                    "Key Detail": "Without treatment, adults risk 25 percent decreased GFR and 17 percent ESRD"
                }
            }
        }
    ]
}
