BRICK = {
    "brick_num": 31,
    "brick_title": "Respiratory Alkalosis",
    "games": [
        {
            "slug": "respiratory_alkalosis_basics",
            "title": "Respiratory Alkalosis Basics",
            "subtitle": "Match each concept to definition, ABG pattern, and key driver",
            "categories": ["Definition", "ABG Pattern", "Key Driver"],
            "data": {
                "Respiratory Alkalosis": {
                    "Definition": "Primary acid-base disorder with reduced PaCO2 and elevated pH",
                    "ABG Pattern": "pH up, PaCO2 down, HCO3- may be normal or down",
                    "Key Driver": "Alveolar ventilation exceeds metabolic CO2 production"
                },
                "Normal pH Range": {
                    "Definition": "Narrow physiologic range needed for normal cellular function",
                    "ABG Pattern": "pH between 7.35 and 7.45",
                    "Key Driver": "Tight regulation of hydrogen ion concentration in body fluids"
                },
                "Volatile Acids": {
                    "Definition": "CO2-derived acids produced continuously by aerobic metabolism",
                    "ABG Pattern": "Reflected by PaCO2 level on blood gas",
                    "Key Driver": "Krebs cycle produces over 15,000 millimoles daily"
                },
                "Non-volatile Acids": {
                    "Definition": "Acids unrelated to CO2 like sulfuric, phosphoric, lactic",
                    "ABG Pattern": "Reflected by serum HCO3- and anion gap",
                    "Key Driver": "Generated by protein metabolism, excreted by kidneys"
                },
                "Bicarbonate Buffer": {
                    "Definition": "Body's primary extracellular buffer system for pH stability",
                    "ABG Pattern": "CO2 + H2O reversibly forms H2CO3 forms HCO3- + H+",
                    "Key Driver": "Carbonic anhydrase catalyzes rapid acid neutralization"
                }
            }
        },
        {
            "slug": "causes_of_respiratory_alkalosis",
            "title": "Causes of Respiratory Alkalosis",
            "subtitle": "Match each cause to mechanism, PO2 status, and example",
            "categories": ["Mechanism", "PO2 Status", "Example"],
            "data": {
                "High Altitude": {
                    "Mechanism": "Low fraction of inspired oxygen reduces alveolar PO2",
                    "PO2 Status": "Low PO2 due to low atmospheric pressure",
                    "Example": "Climber at elevation breathing thin air"
                },
                "Cardiopulmonary Disease": {
                    "Mechanism": "Reduced oxygen diffusion across alveolar membrane",
                    "PO2 Status": "Low PaO2 with low oxygen delivery to tissues",
                    "Example": "CHF, pneumonia, or ARDS causing hypoxemia"
                },
                "Panic Disorder": {
                    "Mechanism": "CNS stimulation triggers hyperventilation without hypoxia",
                    "PO2 Status": "Normal PO2 throughout the episode",
                    "Example": "Most common overall cause of respiratory alkalosis"
                },
                "Hyperthyroidism": {
                    "Mechanism": "Increased metabolic demand drives hyperventilation",
                    "PO2 Status": "Normal PO2 with hypermetabolic state",
                    "Example": "Severe thyroid hormone excess or sepsis"
                },
                "Pregnancy": {
                    "Mechanism": "Increased progestins cause bronchodilation and tidal volume",
                    "PO2 Status": "Normal PO2 with altered hormonal biochemistry",
                    "Example": "Physiologic hyperventilation in gestating patient"
                },
                "Pulmonary Embolism": {
                    "Mechanism": "Clot in pulmonary arteries causing sudden hyperventilation",
                    "PO2 Status": "PO2 may be low or normal depending on case",
                    "Example": "Sudden unexplained alkalosis with possible chest pain"
                }
            }
        },
        {
            "slug": "diagnosis_and_management_alk",
            "title": "Diagnosis and Management",
            "subtitle": "Match each clinical feature to category, finding, and approach",
            "categories": ["Category", "Finding", "Approach"],
            "data": {
                "Clinical Symptoms": {
                    "Category": "Initial presentation of respiratory alkalosis",
                    "Finding": "Hyperventilation, tachypnea, light-headedness, paresthesias",
                    "Approach": "Recognize hypocalcemia symptoms from decreased ionized calcium"
                },
                "Lab Diagnosis": {
                    "Category": "Confirms acid-base disturbance from blood sample",
                    "Finding": "Arterial blood gas shows elevated pH and low PaCO2",
                    "Approach": "Add metabolic panel to assess HCO3- and compensation"
                },
                "Pulse Oximetry": {
                    "Category": "Bedside oxygenation screening test",
                    "Finding": "Distinguishes hypoxemic from nonhypoxemic causes",
                    "Approach": "Essential to rule out hypoxemia driving hyperventilation"
                },
                "Imaging": {
                    "Category": "Radiologic workup for suspected etiology",
                    "Finding": "Chest x-ray for pneumonia, CHF, or pulmonary disease",
                    "Approach": "CT angiography confirms pulmonary embolism if suspected"
                },
                "Renal Compensation": {
                    "Category": "Chronic body response over hours to days",
                    "Finding": "Kidneys excrete bicarbonate to lower elevated pH",
                    "Approach": "Seen only in chronic cases, never fully normalizes pH"
                },
                "Treatment": {
                    "Category": "Management strategy for the disorder",
                    "Finding": "Address underlying cause is the primary goal",
                    "Approach": "Give oxygen for hypoxia, anticoagulation for PE"
                }
            }
        }
    ]
}
